### PR TITLE
Build etherpad-lite snap

### PR DESCRIPTION
**Pull request by dplanella**
The snap now builds correctly, seemingly including all files.

However, the server does not seem to start (or at least http://127.0.0.1:9001/ is not accessible).

Notes:
- I had been looking at @asac's original [etherpad-lite snap](https://github.com/asac/etherpad-lite), which I've changed and adapted to the current snapcraft.yaml syntax
- He actually forked the upstream repo with [two changes](https://github.com/asac/etherpad-lite/commit/21a772999f35b3026b56acd8ef45e6c2bc92dd61):
  - The first one is no longer necessary in this pull request
  - The second one I _think_ is not necessary either

### CODE REVIEW

**Comment by asac** [comment]
find it hard to believe that my changes are not needed anymore... maybe
thats why it doesnt start?

**Comment by asac** [comment]
the other reason why i forked is that i believr getting snapcraft.yaml into
upstream tree is better than external ownership...

**Comment by dplanella** [comment]
@asac: thanks for the comments! Here is some more context on the original post:
- The first change to the upstream code (settings.js) is no longer needed as this branch does not copy over the `settings.json.template` file but defines a new one. The upstream .template file cannot be used as it is due to it hardcoding the database location to /var, which snaps have no access to.
- The second change to the upstream code I couldn't quite follow, but it seems that using the nodejs plugin as it is today already takes care of installing everything in the right locations.

In any case, the current failure to run is due to etherpad trying to write to a R/O location:

```
+ cd /var/snap/etherpad-lite-unofficial/100001
+ exec /snap/etherpad-lite-unofficial/100001/bin/etherpad-lite --settings /snap/etherpad-lite-unofficial/100001/etc/settings.json
[2016-06-08 14:04:54.765] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2016-06-08 14:04:56.998] [ERROR] console - Failed to load '/snap/etherpad-lite-unofficial/100001/lib/node_modules/ep_etherpad-lite/node/hooks/express/static:expressCreateServer' for 'ep_etherpad-lite/static/hooks/expressCreateServer': Error: ENOENT: no such file or directory, stat '/snap/etherpad-lite-unofficial/100001/lib/var/'
```

As per the snapcraft config ownership, I think we all agree that eventually it should be upstream's. But regardless of where development is going on, the first step is to get the snap working again :)

**Comment by asac** [comment]
Hi,

have you checked the real branch?
https://github.com/asac/etherpad-lite/commits/snap-support

2016-06-08 14:07 GMT+02:00 David Planella notifications@github.com:

**Comment by asac** [comment]
Key commits are:

https://github.com/asac/etherpad-lite/commit/d3e12b31e4542eb637b33f2fbbad265d7116e38f
https://github.com/asac/etherpad-lite/commit/8e62911cb2f6be278f70d11c2dc8492e22782f2a

2016-06-08 15:15 GMT+02:00 Alexander Sack asacasa@gmail.com:

**Comment by asac** [comment]
i would just work on top of that branch... and fix the yamnl to be 2.x
compatible...

2016-06-08 15:17 GMT+02:00 Alexander Sack asacasa@gmail.com:

**Comment by asac** [comment]
and fix bin/snappy/runpad to use the new SNAP variables...

2016-06-08 15:17 GMT+02:00 Alexander Sack asacasa@gmail.com:

**Comment by dplanella** [comment]
@asac thanks! We were looking at the snap-related changes on the [develop](https://github.com/asac/etherpad-lite/commits/develop) branch instead of the changes on the [snap-support](https://github.com/asac/etherpad-lite/commits/snap-support) branch.

We've ported the YAML already and changed the wrapper, but I think the only bit we were missing was this upstream change you pointed out: https://github.com/asac/etherpad-lite/commit/8e62911cb2f6be278f70d11c2dc8492e22782f2a

**Pull request merged**
